name: sub

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: 1. 변수출력
      env:
        NAME: 'hojun.lee' 
      run: echo "내 아이디는 $NAME 입니다."
